---
# file: tasks/main.yml
# Top-level installer for Oracle JDK.
#

- include: remove.yml
  when: uninstall

- include: restart.yml
  when: restart and (not uninstall) 

- include: main_install.yml
  when: (not uninstall) and (not restart)


