---
# file: tasks/run-stress-test.yml
# running mixed stress-test with writing in var/log/cassandra/stress_test_mixed_autorate_50r50w_1M
# 

# if it's a new cluster - uncomment
#- include: change-replica.yml 

- name: running mixed stress-test
  command: cassandra-stress mixed ratio\(write=1,read=3\) n=100000 cl=ONE -pop dist=UNIFORM\(1..1000000\) -schema keyspace="keyspace1" -mode native cql3 -rate threads\>=16 threads\<=256 -log file=/var/log/cassandra/stress_test_mixed_autorate_50r50w_1M.log
  register: stressTestLog

- debug: msg="{{ stressTestLog.stdout }}"
- debug: msg="{{ stressTestLog.stderr }}"



